### PR TITLE
Pull request for the Edge 4.17.09 release

### PR DESCRIPTION
**Pull request by sgilsonapigee**

### CODE REVIEW

**Comment by jncd** [comment]
Hi @sgilsonapigee 
I'm seeing merge conflicts in this PR. Can you resolve these merge conflicts and try again? Maybe you didn't have the most recent master branch as the basis for your PR?

**Comment by sgilsonapigee** [comment]
resolved conflicts

**Comment by sgilsonapigee** [comment]
@jncd, do I have to make another pull request? Or is resolving the merge enough?

**Comment by jknostman3** [comment]
@sgilsonapigee Thanks!

**Pull request merged**
